### ISSUE TITLE
NaN geolocations

### ISSUE THREAD

**Issue by charliepnnl** [pnnl/Remote-QA-Web-App#3]
Some photo geolocations are displaying as NaN&deg;NaN&prime;NaN&Prime;.
1) Is this a bug in the code that gets the geolocation from the image metadata? You might find online photo metadata viewers helpful as a double check on the code we are using.
2) If we can not avoid getting Nan, it should be interpreted as if the geolocation were missing.

**Comment by RaeChen07** [comment]
@charliepnnl do you have a photo that you know have a Geolocation but is displaying NaN? If you have it will save me a lot of trouble :)

**Comment by charliepnnl** [comment]
Yes, here is a photo that give NaN values for the geolocation.

![Figure 5 Completed HPWH installation photo](https://user-images.githubusercontent.com/72275714/236329956-fcbdc1ab-f81e-41df-8328-910f3f617aa4.jpg)
